package jp.co.sample.customer.biz.model;

import java.util.List;
import jp.co.sample.customer.biz.model.Rank;
import jp.co.sample.customer.biz.model.RankExample;
import org.apache.ibatis.annotations.Param;


public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int countByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int deleteByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    List<Rank> selectByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    Rank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int updateByExampleSelective(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int updateByPrimaryKeySelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Sat Aug 15 02:45:59 JST 2015
     */
    int updateByPrimaryKey(Rank record);
}